### ISSUE TITLE
The prefix name is duplicated in the schemaLocation typeName

### ISSUE THREAD

**Issue by aperi2007** [MapServer/tinyows#54] opened 2012-12-30 07:22 UTC
Hi,

The GML response to a GetFeature request like this:

http://web.regione.toscana.it/wfsvector/com.rt.wfs.RTmap/wfs?SERVICE=WFS&VERSION=1.0.0&REQUEST=GetFeature&TYPENAME=sita:idcomuni&SRSNAME=EPSG:3003

has a schemaLocation attribute where the Typename has the prefix (read 'sita') duplicated.

This is the response it give:

&lt;wfs:FeatureCollection xsi:schemaLocation="http://www.regione.toscana.it/  
    http://web.regione.toscana.it:80/wfsvector/com.rt.wfs.RTmap/wfs?service=WFS&version=1.0.0&request=DescribeFeatureType&Typename=sita:sita:idcomuni  
    http://www.opengis.net/wfs  
    http://schemas.opengis.net/wfs/1.0.0/WFS-basic.xsd  
    http://www.opengis.net/gml  
    http://schemas.opengis.net/gml/2.1.2/feature.xsd"
&gt;

please, notice the double sita:sita in the typeName attribute.

**Comment by jmckenna** [comment] 2021-06-11 14:24
This seems to be fixed earlier through this commit https://github.com/MapServer/tinyows/commit/f4345f886a5da620a7fe9185c64f8b92c403994c#diff-11417a4218e5fa9d2126912e7411fd9a69e986cc81735dc45914b44ae9879a5a 

I cannot reproduce now.  Closing.

**Closed by jmckenna** 2021-06-11 14:24 UTC
